package br.gov.camara.edemocracia.portlets.graficos.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ContadorAcesso service. Represents a row in the &quot;Graficos_ContadorAcesso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.gov.camara.edemocracia.portlets.graficos.model.impl.ContadorAcessoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.gov.camara.edemocracia.portlets.graficos.model.impl.ContadorAcessoImpl}.
 * </p>
 *
 * @author Robson Miranda
 * @see ContadorAcesso
 * @see br.gov.camara.edemocracia.portlets.graficos.model.impl.ContadorAcessoImpl
 * @see br.gov.camara.edemocracia.portlets.graficos.model.impl.ContadorAcessoModelImpl
 * @generated
 */
public interface ContadorAcessoModel extends BaseModel<ContadorAcesso> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a contador acesso model instance should use the {@link ContadorAcesso} interface instead.
     */

    /**
     * Returns the primary key of this contador acesso.
     *
     * @return the primary key of this contador acesso
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this contador acesso.
     *
     * @param primaryKey the primary key of this contador acesso
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the contador ID of this contador acesso.
     *
     * @return the contador ID of this contador acesso
     */
    public long getContadorId();

    /**
     * Sets the contador ID of this contador acesso.
     *
     * @param contadorId the contador ID of this contador acesso
     */
    public void setContadorId(long contadorId);

    /**
     * Returns the company ID of this contador acesso.
     *
     * @return the company ID of this contador acesso
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this contador acesso.
     *
     * @param companyId the company ID of this contador acesso
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the data of this contador acesso.
     *
     * @return the data of this contador acesso
     */
    public Date getData();

    /**
     * Sets the data of this contador acesso.
     *
     * @param data the data of this contador acesso
     */
    public void setData(Date data);

    /**
     * Returns the data atualizacao of this contador acesso.
     *
     * @return the data atualizacao of this contador acesso
     */
    public Date getDataAtualizacao();

    /**
     * Sets the data atualizacao of this contador acesso.
     *
     * @param dataAtualizacao the data atualizacao of this contador acesso
     */
    public void setDataAtualizacao(Date dataAtualizacao);

    /**
     * Returns the cache of this contador acesso.
     *
     * @return the cache of this contador acesso
     */
    @AutoEscape
    public String getCache();

    /**
     * Sets the cache of this contador acesso.
     *
     * @param cache the cache of this contador acesso
     */
    public void setCache(String cache);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(ContadorAcesso contadorAcesso);

    public int hashCode();

    public CacheModel<ContadorAcesso> toCacheModel();

    public ContadorAcesso toEscapedModel();

    public String toString();

    public String toXmlString();
}
