/**
 * Copyright (c) 2009-2014 Câmara dos Deputados. Todos os direitos reservados.
 *
 * e-Democracia é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro
 * dos termos da Licença Pública Geral Menor GNU como publicada pela Fundação do 
 * Software Livre (FSF); na versão 2.1 da Licença, ou (na sua opinião) qualquer versão.
 *
 * Este programa é distribuído na esperança de que possa ser  útil, mas SEM NENHUMA GARANTIA;
 * sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR.
 * Veja a Licença Pública Geral Menor GNU para maiores detalhes. 
 */
package br.gov.camara.edemocracia.portlets.priorizacao.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Configuracao service. Represents a row in the &quot;PR_Configuracao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.gov.camara.edemocracia.portlets.priorizacao.model.impl.ConfiguracaoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.gov.camara.edemocracia.portlets.priorizacao.model.impl.ConfiguracaoImpl}.
 * </p>
 *
 * @author robson
 * @see Configuracao
 * @see br.gov.camara.edemocracia.portlets.priorizacao.model.impl.ConfiguracaoImpl
 * @see br.gov.camara.edemocracia.portlets.priorizacao.model.impl.ConfiguracaoModelImpl
 * @generated
 */
public interface ConfiguracaoModel extends BaseModel<Configuracao> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a configuracao model instance should use the {@link Configuracao} interface instead.
     */

    /**
     * Returns the primary key of this configuracao.
     *
     * @return the primary key of this configuracao
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this configuracao.
     *
     * @param primaryKey the primary key of this configuracao
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the configuracao ID of this configuracao.
     *
     * @return the configuracao ID of this configuracao
     */
    public long getConfiguracaoId();

    /**
     * Sets the configuracao ID of this configuracao.
     *
     * @param configuracaoId the configuracao ID of this configuracao
     */
    public void setConfiguracaoId(long configuracaoId);

    /**
     * Returns the company ID of this configuracao.
     *
     * @return the company ID of this configuracao
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this configuracao.
     *
     * @param companyId the company ID of this configuracao
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this configuracao.
     *
     * @return the group ID of this configuracao
     */
    public long getGroupId();

    /**
     * Sets the group ID of this configuracao.
     *
     * @param groupId the group ID of this configuracao
     */
    public void setGroupId(long groupId);

    /**
     * Returns the maximo votos of this configuracao.
     *
     * @return the maximo votos of this configuracao
     */
    public int getMaximoVotos();

    /**
     * Sets the maximo votos of this configuracao.
     *
     * @param maximoVotos the maximo votos of this configuracao
     */
    public void setMaximoVotos(int maximoVotos);

    /**
     * Returns the max votos proposta of this configuracao.
     *
     * @return the max votos proposta of this configuracao
     */
    public int getMaxVotosProposta();

    /**
     * Sets the max votos proposta of this configuracao.
     *
     * @param maxVotosProposta the max votos proposta of this configuracao
     */
    public void setMaxVotosProposta(int maxVotosProposta);

    /**
     * Returns the votacao aberta of this configuracao.
     *
     * @return the votacao aberta of this configuracao
     */
    public boolean getVotacaoAberta();

    /**
     * Returns <code>true</code> if this configuracao is votacao aberta.
     *
     * @return <code>true</code> if this configuracao is votacao aberta; <code>false</code> otherwise
     */
    public boolean isVotacaoAberta();

    /**
     * Sets whether this configuracao is votacao aberta.
     *
     * @param votacaoAberta the votacao aberta of this configuracao
     */
    public void setVotacaoAberta(boolean votacaoAberta);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Configuracao configuracao);

    public int hashCode();

    public CacheModel<Configuracao> toCacheModel();

    public Configuracao toEscapedModel();

    public String toString();

    public String toXmlString();
}
