package br.gov.camara.edemocracia.portlets.graficos.model.impl;

import br.gov.camara.edemocracia.portlets.graficos.model.ContadorAcesso;
import br.gov.camara.edemocracia.portlets.graficos.service.ContadorAcessoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ContadorAcesso service. Represents a row in the &quot;Graficos_ContadorAcesso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContadorAcessoImpl}.
 * </p>
 *
 * @author Robson Miranda
 * @see ContadorAcessoImpl
 * @see br.gov.camara.edemocracia.portlets.graficos.model.ContadorAcesso
 * @generated
 */
public abstract class ContadorAcessoBaseImpl extends ContadorAcessoModelImpl
    implements ContadorAcesso {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a contador acesso model instance should use the {@link ContadorAcesso} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ContadorAcessoLocalServiceUtil.addContadorAcesso(this);
        } else {
            ContadorAcessoLocalServiceUtil.updateContadorAcesso(this);
        }
    }
}
