package br.gov.camara.edemocracia.portlets.priorizacao.model.impl;

import br.gov.camara.edemocracia.portlets.priorizacao.model.Configuracao;
import br.gov.camara.edemocracia.portlets.priorizacao.service.ConfiguracaoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Configuracao service. Represents a row in the &quot;PR_Configuracao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConfiguracaoImpl}.
 * </p>
 *
 * @author robson
 * @see ConfiguracaoImpl
 * @see br.gov.camara.edemocracia.portlets.priorizacao.model.Configuracao
 * @generated
 */
public abstract class ConfiguracaoBaseImpl extends ConfiguracaoModelImpl
    implements Configuracao {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a configuracao model instance should use the {@link Configuracao} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ConfiguracaoLocalServiceUtil.addConfiguracao(this);
        } else {
            ConfiguracaoLocalServiceUtil.updateConfiguracao(this);
        }
    }
}
