package br.gov.camara.edemocracia.portlets.priorizacao.model.impl;

import br.gov.camara.edemocracia.portlets.priorizacao.model.Proposta;
import br.gov.camara.edemocracia.portlets.priorizacao.service.PropostaLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Proposta service. Represents a row in the &quot;PR_Proposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PropostaImpl}.
 * </p>
 *
 * @author robson
 * @see PropostaImpl
 * @see br.gov.camara.edemocracia.portlets.priorizacao.model.Proposta
 * @generated
 */
public abstract class PropostaBaseImpl extends PropostaModelImpl
    implements Proposta {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a proposta model instance should use the {@link Proposta} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            PropostaLocalServiceUtil.addProposta(this);
        } else {
            PropostaLocalServiceUtil.updateProposta(this);
        }
    }
}
