package br.gov.camara.edemocracia.portlets.priorizacao.model.impl;

import br.gov.camara.edemocracia.portlets.priorizacao.model.Voto;
import br.gov.camara.edemocracia.portlets.priorizacao.service.VotoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Voto service. Represents a row in the &quot;PR_Voto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VotoImpl}.
 * </p>
 *
 * @author robson
 * @see VotoImpl
 * @see br.gov.camara.edemocracia.portlets.priorizacao.model.Voto
 * @generated
 */
public abstract class VotoBaseImpl extends VotoModelImpl implements Voto {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a voto model instance should use the {@link Voto} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            VotoLocalServiceUtil.addVoto(this);
        } else {
            VotoLocalServiceUtil.updateVoto(this);
        }
    }
}
