/**
 * Copyright (c) 2009-2014 Câmara dos Deputados. Todos os direitos reservados.
 *
 * e-Democracia é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro
 * dos termos da Licença Pública Geral Menor GNU como publicada pela Fundação do 
 * Software Livre (FSF); na versão 2.1 da Licença, ou (na sua opinião) qualquer versão.
 *
 * Este programa é distribuído na esperança de que possa ser  útil, mas SEM NENHUMA GARANTIA;
 * sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR.
 * Veja a Licença Pública Geral Menor GNU para maiores detalhes. 
 */
package br.gov.camara.edemocracia.portlets.chat.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ChatRoomVideo service. Represents a row in the &quot;CDChat_ChatRoomVideo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.gov.camara.edemocracia.portlets.chat.model.impl.ChatRoomVideoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.gov.camara.edemocracia.portlets.chat.model.impl.ChatRoomVideoImpl}.
 * </p>
 *
 * @author Ricardo Lima
 * @see ChatRoomVideo
 * @see br.gov.camara.edemocracia.portlets.chat.model.impl.ChatRoomVideoImpl
 * @see br.gov.camara.edemocracia.portlets.chat.model.impl.ChatRoomVideoModelImpl
 * @generated
 */
public interface ChatRoomVideoModel extends BaseModel<ChatRoomVideo> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a chat room video model instance should use the {@link ChatRoomVideo} interface instead.
     */

    /**
     * Returns the primary key of this chat room video.
     *
     * @return the primary key of this chat room video
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this chat room video.
     *
     * @param primaryKey the primary key of this chat room video
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the video ID of this chat room video.
     *
     * @return the video ID of this chat room video
     */
    public long getVideoId();

    /**
     * Sets the video ID of this chat room video.
     *
     * @param videoId the video ID of this chat room video
     */
    public void setVideoId(long videoId);

    /**
     * Returns the video title of this chat room video.
     *
     * @return the video title of this chat room video
     */
    @AutoEscape
    public String getVideoTitle();

    /**
     * Sets the video title of this chat room video.
     *
     * @param videoTitle the video title of this chat room video
     */
    public void setVideoTitle(String videoTitle);

    /**
     * Returns the video subtitle of this chat room video.
     *
     * @return the video subtitle of this chat room video
     */
    @AutoEscape
    public String getVideoSubtitle();

    /**
     * Sets the video subtitle of this chat room video.
     *
     * @param videoSubtitle the video subtitle of this chat room video
     */
    public void setVideoSubtitle(String videoSubtitle);

    /**
     * Returns the video description of this chat room video.
     *
     * @return the video description of this chat room video
     */
    @AutoEscape
    public String getVideoDescription();

    /**
     * Sets the video description of this chat room video.
     *
     * @param videoDescription the video description of this chat room video
     */
    public void setVideoDescription(String videoDescription);

    /**
     * Returns the video enabled of this chat room video.
     *
     * @return the video enabled of this chat room video
     */
    public boolean getVideoEnabled();

    /**
     * Returns <code>true</code> if this chat room video is video enabled.
     *
     * @return <code>true</code> if this chat room video is video enabled; <code>false</code> otherwise
     */
    public boolean isVideoEnabled();

    /**
     * Sets whether this chat room video is video enabled.
     *
     * @param videoEnabled the video enabled of this chat room video
     */
    public void setVideoEnabled(boolean videoEnabled);

    /**
     * Returns the video url of this chat room video.
     *
     * @return the video url of this chat room video
     */
    @AutoEscape
    public String getVideoUrl();

    /**
     * Sets the video url of this chat room video.
     *
     * @param videoUrl the video url of this chat room video
     */
    public void setVideoUrl(String videoUrl);

    /**
     * Returns the video type of this chat room video.
     *
     * @return the video type of this chat room video
     */
    @AutoEscape
    public String getVideoType();

    /**
     * Sets the video type of this chat room video.
     *
     * @param videoType the video type of this chat room video
     */
    public void setVideoType(String videoType);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(ChatRoomVideo chatRoomVideo);

    public int hashCode();

    public CacheModel<ChatRoomVideo> toCacheModel();

    public ChatRoomVideo toEscapedModel();

    public String toString();

    public String toXmlString();
}
