/**
 * Copyright (c) 2009-2014 Câmara dos Deputados. Todos os direitos reservados.
 *
 * e-Democracia é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro
 * dos termos da Licença Pública Geral Menor GNU como publicada pela Fundação do 
 * Software Livre (FSF); na versão 2.1 da Licença, ou (na sua opinião) qualquer versão.
 *
 * Este programa é distribuído na esperança de que possa ser  útil, mas SEM NENHUMA GARANTIA;
 * sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR.
 * Veja a Licença Pública Geral Menor GNU para maiores detalhes. 
 */
package br.gov.camara.edemocracia.portlets.wikilegis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Contribuicao service. Represents a row in the &quot;CDWL_Contribuicao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.gov.camara.edemocracia.portlets.wikilegis.model.impl.ContribuicaoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.gov.camara.edemocracia.portlets.wikilegis.model.impl.ContribuicaoImpl}.
 * </p>
 *
 * @author robson
 * @see Contribuicao
 * @see br.gov.camara.edemocracia.portlets.wikilegis.model.impl.ContribuicaoImpl
 * @see br.gov.camara.edemocracia.portlets.wikilegis.model.impl.ContribuicaoModelImpl
 * @generated
 */
public interface ContribuicaoModel extends BaseModel<Contribuicao> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a contribuicao model instance should use the {@link Contribuicao} interface instead.
     */

    /**
     * Returns the primary key of this contribuicao.
     *
     * @return the primary key of this contribuicao
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this contribuicao.
     *
     * @param primaryKey the primary key of this contribuicao
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the contribuicao ID of this contribuicao.
     *
     * @return the contribuicao ID of this contribuicao
     */
    public long getContribuicaoId();

    /**
     * Sets the contribuicao ID of this contribuicao.
     *
     * @param contribuicaoId the contribuicao ID of this contribuicao
     */
    public void setContribuicaoId(long contribuicaoId);

    /**
     * Returns the artigo ID of this contribuicao.
     *
     * @return the artigo ID of this contribuicao
     */
    public long getArtigoId();

    /**
     * Sets the artigo ID of this contribuicao.
     *
     * @param artigoId the artigo ID of this contribuicao
     */
    public void setArtigoId(long artigoId);

    /**
     * Returns the texto of this contribuicao.
     *
     * @return the texto of this contribuicao
     */
    @AutoEscape
    public String getTexto();

    /**
     * Sets the texto of this contribuicao.
     *
     * @param texto the texto of this contribuicao
     */
    public void setTexto(String texto);

    /**
     * Returns the descricao of this contribuicao.
     *
     * @return the descricao of this contribuicao
     */
    @AutoEscape
    public String getDescricao();

    /**
     * Sets the descricao of this contribuicao.
     *
     * @param descricao the descricao of this contribuicao
     */
    public void setDescricao(String descricao);

    /**
     * Returns the data of this contribuicao.
     *
     * @return the data of this contribuicao
     */
    public Date getData();

    /**
     * Sets the data of this contribuicao.
     *
     * @param data the data of this contribuicao
     */
    public void setData(Date data);

    /**
     * Returns the user ID of this contribuicao.
     *
     * @return the user ID of this contribuicao
     */
    public long getUserId();

    /**
     * Sets the user ID of this contribuicao.
     *
     * @param userId the user ID of this contribuicao
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this contribuicao.
     *
     * @return the user uuid of this contribuicao
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this contribuicao.
     *
     * @param userUuid the user uuid of this contribuicao
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this contribuicao.
     *
     * @return the user name of this contribuicao
     */
    @AutoEscape
    public String getUserName();

    /**
     * Sets the user name of this contribuicao.
     *
     * @param userName the user name of this contribuicao
     */
    public void setUserName(String userName);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Contribuicao contribuicao);

    public int hashCode();

    public CacheModel<Contribuicao> toCacheModel();

    public Contribuicao toEscapedModel();

    public String toString();

    public String toXmlString();
}
