package br.gov.camara.edemocracia.portlets.wikilegis.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Estrutura service. Represents a row in the &quot;CDWL_Estrutura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.gov.camara.edemocracia.portlets.wikilegis.model.impl.EstruturaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.gov.camara.edemocracia.portlets.wikilegis.model.impl.EstruturaImpl}.
 * </p>
 *
 * @author robson
 * @see Estrutura
 * @see br.gov.camara.edemocracia.portlets.wikilegis.model.impl.EstruturaImpl
 * @see br.gov.camara.edemocracia.portlets.wikilegis.model.impl.EstruturaModelImpl
 * @generated
 */
public interface EstruturaModel extends BaseModel<Estrutura> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a estrutura model instance should use the {@link Estrutura} interface instead.
     */

    /**
     * Returns the primary key of this estrutura.
     *
     * @return the primary key of this estrutura
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this estrutura.
     *
     * @param primaryKey the primary key of this estrutura
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the estrutura ID of this estrutura.
     *
     * @return the estrutura ID of this estrutura
     */
    public long getEstruturaId();

    /**
     * Sets the estrutura ID of this estrutura.
     *
     * @param estruturaId the estrutura ID of this estrutura
     */
    public void setEstruturaId(long estruturaId);

    /**
     * Returns the company ID of this estrutura.
     *
     * @return the company ID of this estrutura
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this estrutura.
     *
     * @param companyId the company ID of this estrutura
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this estrutura.
     *
     * @return the group ID of this estrutura
     */
    public long getGroupId();

    /**
     * Sets the group ID of this estrutura.
     *
     * @param groupId the group ID of this estrutura
     */
    public void setGroupId(long groupId);

    /**
     * Returns the texto of this estrutura.
     *
     * @return the texto of this estrutura
     */
    @AutoEscape
    public String getTexto();

    /**
     * Sets the texto of this estrutura.
     *
     * @param texto the texto of this estrutura
     */
    public void setTexto(String texto);

    /**
     * Returns the ordem of this estrutura.
     *
     * @return the ordem of this estrutura
     */
    public int getOrdem();

    /**
     * Sets the ordem of this estrutura.
     *
     * @param ordem the ordem of this estrutura
     */
    public void setOrdem(int ordem);

    /**
     * Returns the pai estrutura ID of this estrutura.
     *
     * @return the pai estrutura ID of this estrutura
     */
    public long getPaiEstruturaId();

    /**
     * Sets the pai estrutura ID of this estrutura.
     *
     * @param paiEstruturaId the pai estrutura ID of this estrutura
     */
    public void setPaiEstruturaId(long paiEstruturaId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Estrutura estrutura);

    public int hashCode();

    public CacheModel<Estrutura> toCacheModel();

    public Estrutura toEscapedModel();

    public String toString();

    public String toXmlString();
}
