/**
 * Copyright (c) 2009-2014 Câmara dos Deputados. Todos os direitos reservados.
 *
 * e-Democracia é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro
 * dos termos da Licença Pública Geral Menor GNU como publicada pela Fundação do 
 * Software Livre (FSF); na versão 2.1 da Licença, ou (na sua opinião) qualquer versão.
 *
 * Este programa é distribuído na esperança de que possa ser  útil, mas SEM NENHUMA GARANTIA;
 * sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR.
 * Veja a Licença Pública Geral Menor GNU para maiores detalhes. 
 */
package br.gov.camara.edemocracia.portlets.guiadiscussao.model.impl;

import br.gov.camara.edemocracia.portlets.guiadiscussao.model.Configuracao;
import br.gov.camara.edemocracia.portlets.guiadiscussao.model.ConfiguracaoModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Configuracao service. Represents a row in the &quot;GD_Configuracao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.gov.camara.edemocracia.portlets.guiadiscussao.model.ConfiguracaoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConfiguracaoImpl}.
 * </p>
 *
 * @author Robson
 * @see ConfiguracaoImpl
 * @see br.gov.camara.edemocracia.portlets.guiadiscussao.model.Configuracao
 * @see br.gov.camara.edemocracia.portlets.guiadiscussao.model.ConfiguracaoModel
 * @generated
 */
public class ConfiguracaoModelImpl extends BaseModelImpl<Configuracao>
    implements ConfiguracaoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a configuracao model instance should use the {@link br.gov.camara.edemocracia.portlets.guiadiscussao.model.Configuracao} interface instead.
     */
    public static final String TABLE_NAME = "GD_Configuracao";
    public static final Object[][] TABLE_COLUMNS = {
            { "configuracaoId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "faseAtualId", Types.BIGINT },
            { "textoBanner", Types.VARCHAR },
            { "imagemIdBanner", Types.BIGINT },
            { "urlBanner", Types.VARCHAR },
            { "urlExterna", Types.BOOLEAN },
            { "tituloBanner", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table GD_Configuracao (configuracaoId LONG not null primary key,groupId LONG,faseAtualId LONG,textoBanner VARCHAR(75) null,imagemIdBanner LONG,urlBanner VARCHAR(300) null,urlExterna BOOLEAN,tituloBanner VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table GD_Configuracao";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.br.gov.camara.edemocracia.portlets.guiadiscussao.model.Configuracao"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.br.gov.camara.edemocracia.portlets.guiadiscussao.model.Configuracao"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.br.gov.camara.edemocracia.portlets.guiadiscussao.model.Configuracao"),
            true);
    public static long GROUPID_COLUMN_BITMASK = 1L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.br.gov.camara.edemocracia.portlets.guiadiscussao.model.Configuracao"));
    private static ClassLoader _classLoader = Configuracao.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            Configuracao.class
        };
    private long _configuracaoId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _faseAtualId;
    private String _textoBanner;
    private long _imagemIdBanner;
    private String _urlBanner;
    private boolean _urlExterna;
    private String _tituloBanner;
    private long _columnBitmask;
    private Configuracao _escapedModelProxy;

    public ConfiguracaoModelImpl() {
    }

    public long getPrimaryKey() {
        return _configuracaoId;
    }

    public void setPrimaryKey(long primaryKey) {
        setConfiguracaoId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_configuracaoId);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return Configuracao.class;
    }

    public String getModelClassName() {
        return Configuracao.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("configuracaoId", getConfiguracaoId());
        attributes.put("groupId", getGroupId());
        attributes.put("faseAtualId", getFaseAtualId());
        attributes.put("textoBanner", getTextoBanner());
        attributes.put("imagemIdBanner", getImagemIdBanner());
        attributes.put("urlBanner", getUrlBanner());
        attributes.put("urlExterna", getUrlExterna());
        attributes.put("tituloBanner", getTituloBanner());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long configuracaoId = (Long) attributes.get("configuracaoId");

        if (configuracaoId != null) {
            setConfiguracaoId(configuracaoId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long faseAtualId = (Long) attributes.get("faseAtualId");

        if (faseAtualId != null) {
            setFaseAtualId(faseAtualId);
        }

        String textoBanner = (String) attributes.get("textoBanner");

        if (textoBanner != null) {
            setTextoBanner(textoBanner);
        }

        Long imagemIdBanner = (Long) attributes.get("imagemIdBanner");

        if (imagemIdBanner != null) {
            setImagemIdBanner(imagemIdBanner);
        }

        String urlBanner = (String) attributes.get("urlBanner");

        if (urlBanner != null) {
            setUrlBanner(urlBanner);
        }

        Boolean urlExterna = (Boolean) attributes.get("urlExterna");

        if (urlExterna != null) {
            setUrlExterna(urlExterna);
        }

        String tituloBanner = (String) attributes.get("tituloBanner");

        if (tituloBanner != null) {
            setTituloBanner(tituloBanner);
        }
    }

    public long getConfiguracaoId() {
        return _configuracaoId;
    }

    public void setConfiguracaoId(long configuracaoId) {
        _configuracaoId = configuracaoId;
    }

    public long getGroupId() {
        return _groupId;
    }

    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    public long getFaseAtualId() {
        return _faseAtualId;
    }

    public void setFaseAtualId(long faseAtualId) {
        _faseAtualId = faseAtualId;
    }

    public String getTextoBanner() {
        if (_textoBanner == null) {
            return StringPool.BLANK;
        } else {
            return _textoBanner;
        }
    }

    public void setTextoBanner(String textoBanner) {
        _textoBanner = textoBanner;
    }

    public long getImagemIdBanner() {
        return _imagemIdBanner;
    }

    public void setImagemIdBanner(long imagemIdBanner) {
        _imagemIdBanner = imagemIdBanner;
    }

    public String getUrlBanner() {
        if (_urlBanner == null) {
            return StringPool.BLANK;
        } else {
            return _urlBanner;
        }
    }

    public void setUrlBanner(String urlBanner) {
        _urlBanner = urlBanner;
    }

    public boolean getUrlExterna() {
        return _urlExterna;
    }

    public boolean isUrlExterna() {
        return _urlExterna;
    }

    public void setUrlExterna(boolean urlExterna) {
        _urlExterna = urlExterna;
    }

    public String getTituloBanner() {
        if (_tituloBanner == null) {
            return StringPool.BLANK;
        } else {
            return _tituloBanner;
        }
    }

    public void setTituloBanner(String tituloBanner) {
        _tituloBanner = tituloBanner;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Configuracao.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Configuracao toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (Configuracao) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public Object clone() {
        ConfiguracaoImpl configuracaoImpl = new ConfiguracaoImpl();

        configuracaoImpl.setConfiguracaoId(getConfiguracaoId());
        configuracaoImpl.setGroupId(getGroupId());
        configuracaoImpl.setFaseAtualId(getFaseAtualId());
        configuracaoImpl.setTextoBanner(getTextoBanner());
        configuracaoImpl.setImagemIdBanner(getImagemIdBanner());
        configuracaoImpl.setUrlBanner(getUrlBanner());
        configuracaoImpl.setUrlExterna(getUrlExterna());
        configuracaoImpl.setTituloBanner(getTituloBanner());

        configuracaoImpl.resetOriginalValues();

        return configuracaoImpl;
    }

    public int compareTo(Configuracao configuracao) {
        long primaryKey = configuracao.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Configuracao configuracao = null;

        try {
            configuracao = (Configuracao) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = configuracao.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        ConfiguracaoModelImpl configuracaoModelImpl = this;

        configuracaoModelImpl._originalGroupId = configuracaoModelImpl._groupId;

        configuracaoModelImpl._setOriginalGroupId = false;

        configuracaoModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Configuracao> toCacheModel() {
        ConfiguracaoCacheModel configuracaoCacheModel = new ConfiguracaoCacheModel();

        configuracaoCacheModel.configuracaoId = getConfiguracaoId();

        configuracaoCacheModel.groupId = getGroupId();

        configuracaoCacheModel.faseAtualId = getFaseAtualId();

        configuracaoCacheModel.textoBanner = getTextoBanner();

        String textoBanner = configuracaoCacheModel.textoBanner;

        if ((textoBanner != null) && (textoBanner.length() == 0)) {
            configuracaoCacheModel.textoBanner = null;
        }

        configuracaoCacheModel.imagemIdBanner = getImagemIdBanner();

        configuracaoCacheModel.urlBanner = getUrlBanner();

        String urlBanner = configuracaoCacheModel.urlBanner;

        if ((urlBanner != null) && (urlBanner.length() == 0)) {
            configuracaoCacheModel.urlBanner = null;
        }

        configuracaoCacheModel.urlExterna = getUrlExterna();

        configuracaoCacheModel.tituloBanner = getTituloBanner();

        String tituloBanner = configuracaoCacheModel.tituloBanner;

        if ((tituloBanner != null) && (tituloBanner.length() == 0)) {
            configuracaoCacheModel.tituloBanner = null;
        }

        return configuracaoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(17);

        sb.append("{configuracaoId=");
        sb.append(getConfiguracaoId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", faseAtualId=");
        sb.append(getFaseAtualId());
        sb.append(", textoBanner=");
        sb.append(getTextoBanner());
        sb.append(", imagemIdBanner=");
        sb.append(getImagemIdBanner());
        sb.append(", urlBanner=");
        sb.append(getUrlBanner());
        sb.append(", urlExterna=");
        sb.append(getUrlExterna());
        sb.append(", tituloBanner=");
        sb.append(getTituloBanner());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(28);

        sb.append("<model><model-name>");
        sb.append(
            "br.gov.camara.edemocracia.portlets.guiadiscussao.model.Configuracao");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>configuracaoId</column-name><column-value><![CDATA[");
        sb.append(getConfiguracaoId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>faseAtualId</column-name><column-value><![CDATA[");
        sb.append(getFaseAtualId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>textoBanner</column-name><column-value><![CDATA[");
        sb.append(getTextoBanner());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>imagemIdBanner</column-name><column-value><![CDATA[");
        sb.append(getImagemIdBanner());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>urlBanner</column-name><column-value><![CDATA[");
        sb.append(getUrlBanner());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>urlExterna</column-name><column-value><![CDATA[");
        sb.append(getUrlExterna());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>tituloBanner</column-name><column-value><![CDATA[");
        sb.append(getTituloBanner());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
