package br.gov.camara.edemocracia.portlets.guiadiscussao.model.impl;

import br.gov.camara.edemocracia.portlets.guiadiscussao.model.Fase;
import br.gov.camara.edemocracia.portlets.guiadiscussao.service.FaseLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Fase service. Represents a row in the &quot;GD_Fase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FaseImpl}.
 * </p>
 *
 * @author Robson
 * @see FaseImpl
 * @see br.gov.camara.edemocracia.portlets.guiadiscussao.model.Fase
 * @generated
 */
public abstract class FaseBaseImpl extends FaseModelImpl implements Fase {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a fase model instance should use the {@link Fase} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            FaseLocalServiceUtil.addFase(this);
        } else {
            FaseLocalServiceUtil.updateFase(this);
        }
    }
}
