package br.gov.camara.edemocracia.portlets.wikilegis.model.impl;

import br.gov.camara.edemocracia.portlets.wikilegis.model.Artigo;
import br.gov.camara.edemocracia.portlets.wikilegis.model.ArtigoModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Artigo service. Represents a row in the &quot;CDWL_Artigo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.gov.camara.edemocracia.portlets.wikilegis.model.ArtigoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArtigoImpl}.
 * </p>
 *
 * @author robson
 * @see ArtigoImpl
 * @see br.gov.camara.edemocracia.portlets.wikilegis.model.Artigo
 * @see br.gov.camara.edemocracia.portlets.wikilegis.model.ArtigoModel
 * @generated
 */
public class ArtigoModelImpl extends BaseModelImpl<Artigo>
    implements ArtigoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a artigo model instance should use the {@link br.gov.camara.edemocracia.portlets.wikilegis.model.Artigo} interface instead.
     */
    public static final String TABLE_NAME = "CDWL_Artigo";
    public static final Object[][] TABLE_COLUMNS = {
            { "artigoId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "estruturaId", Types.BIGINT },
            { "ordem", Types.INTEGER },
            { "texto", Types.VARCHAR },
            { "legislacaoVigente", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table CDWL_Artigo (artigoId LONG not null primary key,companyId LONG,groupId LONG,estruturaId LONG,ordem INTEGER,texto TEXT null,legislacaoVigente TEXT null)";
    public static final String TABLE_SQL_DROP = "drop table CDWL_Artigo";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.br.gov.camara.edemocracia.portlets.wikilegis.model.Artigo"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.br.gov.camara.edemocracia.portlets.wikilegis.model.Artigo"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.br.gov.camara.edemocracia.portlets.wikilegis.model.Artigo"),
            true);
    public static long ESTRUTURAID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.br.gov.camara.edemocracia.portlets.wikilegis.model.Artigo"));
    private static ClassLoader _classLoader = Artigo.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            Artigo.class
        };
    private long _artigoId;
    private long _companyId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _estruturaId;
    private long _originalEstruturaId;
    private boolean _setOriginalEstruturaId;
    private int _ordem;
    private String _texto;
    private String _legislacaoVigente;
    private long _columnBitmask;
    private Artigo _escapedModelProxy;

    public ArtigoModelImpl() {
    }

    public long getPrimaryKey() {
        return _artigoId;
    }

    public void setPrimaryKey(long primaryKey) {
        setArtigoId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_artigoId);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return Artigo.class;
    }

    public String getModelClassName() {
        return Artigo.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("artigoId", getArtigoId());
        attributes.put("companyId", getCompanyId());
        attributes.put("groupId", getGroupId());
        attributes.put("estruturaId", getEstruturaId());
        attributes.put("ordem", getOrdem());
        attributes.put("texto", getTexto());
        attributes.put("legislacaoVigente", getLegislacaoVigente());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long artigoId = (Long) attributes.get("artigoId");

        if (artigoId != null) {
            setArtigoId(artigoId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long estruturaId = (Long) attributes.get("estruturaId");

        if (estruturaId != null) {
            setEstruturaId(estruturaId);
        }

        Integer ordem = (Integer) attributes.get("ordem");

        if (ordem != null) {
            setOrdem(ordem);
        }

        String texto = (String) attributes.get("texto");

        if (texto != null) {
            setTexto(texto);
        }

        String legislacaoVigente = (String) attributes.get("legislacaoVigente");

        if (legislacaoVigente != null) {
            setLegislacaoVigente(legislacaoVigente);
        }
    }

    public long getArtigoId() {
        return _artigoId;
    }

    public void setArtigoId(long artigoId) {
        _artigoId = artigoId;
    }

    public long getCompanyId() {
        return _companyId;
    }

    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    public long getGroupId() {
        return _groupId;
    }

    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    public long getEstruturaId() {
        return _estruturaId;
    }

    public void setEstruturaId(long estruturaId) {
        _columnBitmask |= ESTRUTURAID_COLUMN_BITMASK;

        if (!_setOriginalEstruturaId) {
            _setOriginalEstruturaId = true;

            _originalEstruturaId = _estruturaId;
        }

        _estruturaId = estruturaId;
    }

    public long getOriginalEstruturaId() {
        return _originalEstruturaId;
    }

    public int getOrdem() {
        return _ordem;
    }

    public void setOrdem(int ordem) {
        _ordem = ordem;
    }

    public String getTexto() {
        if (_texto == null) {
            return StringPool.BLANK;
        } else {
            return _texto;
        }
    }

    public void setTexto(String texto) {
        _texto = texto;
    }

    public String getLegislacaoVigente() {
        if (_legislacaoVigente == null) {
            return StringPool.BLANK;
        } else {
            return _legislacaoVigente;
        }
    }

    public void setLegislacaoVigente(String legislacaoVigente) {
        _legislacaoVigente = legislacaoVigente;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Artigo.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Artigo toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (Artigo) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public Object clone() {
        ArtigoImpl artigoImpl = new ArtigoImpl();

        artigoImpl.setArtigoId(getArtigoId());
        artigoImpl.setCompanyId(getCompanyId());
        artigoImpl.setGroupId(getGroupId());
        artigoImpl.setEstruturaId(getEstruturaId());
        artigoImpl.setOrdem(getOrdem());
        artigoImpl.setTexto(getTexto());
        artigoImpl.setLegislacaoVigente(getLegislacaoVigente());

        artigoImpl.resetOriginalValues();

        return artigoImpl;
    }

    public int compareTo(Artigo artigo) {
        long primaryKey = artigo.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Artigo artigo = null;

        try {
            artigo = (Artigo) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = artigo.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        ArtigoModelImpl artigoModelImpl = this;

        artigoModelImpl._originalGroupId = artigoModelImpl._groupId;

        artigoModelImpl._setOriginalGroupId = false;

        artigoModelImpl._originalEstruturaId = artigoModelImpl._estruturaId;

        artigoModelImpl._setOriginalEstruturaId = false;

        artigoModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Artigo> toCacheModel() {
        ArtigoCacheModel artigoCacheModel = new ArtigoCacheModel();

        artigoCacheModel.artigoId = getArtigoId();

        artigoCacheModel.companyId = getCompanyId();

        artigoCacheModel.groupId = getGroupId();

        artigoCacheModel.estruturaId = getEstruturaId();

        artigoCacheModel.ordem = getOrdem();

        artigoCacheModel.texto = getTexto();

        String texto = artigoCacheModel.texto;

        if ((texto != null) && (texto.length() == 0)) {
            artigoCacheModel.texto = null;
        }

        artigoCacheModel.legislacaoVigente = getLegislacaoVigente();

        String legislacaoVigente = artigoCacheModel.legislacaoVigente;

        if ((legislacaoVigente != null) && (legislacaoVigente.length() == 0)) {
            artigoCacheModel.legislacaoVigente = null;
        }

        return artigoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(15);

        sb.append("{artigoId=");
        sb.append(getArtigoId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", estruturaId=");
        sb.append(getEstruturaId());
        sb.append(", ordem=");
        sb.append(getOrdem());
        sb.append(", texto=");
        sb.append(getTexto());
        sb.append(", legislacaoVigente=");
        sb.append(getLegislacaoVigente());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(25);

        sb.append("<model><model-name>");
        sb.append("br.gov.camara.edemocracia.portlets.wikilegis.model.Artigo");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>artigoId</column-name><column-value><![CDATA[");
        sb.append(getArtigoId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>estruturaId</column-name><column-value><![CDATA[");
        sb.append(getEstruturaId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ordem</column-name><column-value><![CDATA[");
        sb.append(getOrdem());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>texto</column-name><column-value><![CDATA[");
        sb.append(getTexto());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>legislacaoVigente</column-name><column-value><![CDATA[");
        sb.append(getLegislacaoVigente());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
