package br.gov.camara.edemocracia.portlets.wikilegis.model.impl;

import br.gov.camara.edemocracia.portlets.wikilegis.model.Contribuicao;
import br.gov.camara.edemocracia.portlets.wikilegis.service.ContribuicaoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Contribuicao service. Represents a row in the &quot;CDWL_Contribuicao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContribuicaoImpl}.
 * </p>
 *
 * @author robson
 * @see ContribuicaoImpl
 * @see br.gov.camara.edemocracia.portlets.wikilegis.model.Contribuicao
 * @generated
 */
public abstract class ContribuicaoBaseImpl extends ContribuicaoModelImpl
    implements Contribuicao {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a contribuicao model instance should use the {@link Contribuicao} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ContribuicaoLocalServiceUtil.addContribuicao(this);
        } else {
            ContribuicaoLocalServiceUtil.updateContribuicao(this);
        }
    }
}
