/**
 * Copyright (c) 2009-2014 Câmara dos Deputados. Todos os direitos reservados.
 *
 * e-Democracia é um software livre; você pode redistribuí-lo e/ou modificá-lo dentro
 * dos termos da Licença Pública Geral Menor GNU como publicada pela Fundação do 
 * Software Livre (FSF); na versão 2.1 da Licença, ou (na sua opinião) qualquer versão.
 *
 * Este programa é distribuído na esperança de que possa ser  útil, mas SEM NENHUMA GARANTIA;
 * sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR.
 * Veja a Licença Pública Geral Menor GNU para maiores detalhes. 
 */
package br.gov.camara.edemocracia.portlets.wikilegis.model.impl;

import br.gov.camara.edemocracia.portlets.wikilegis.model.Estrutura;
import br.gov.camara.edemocracia.portlets.wikilegis.model.EstruturaModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Estrutura service. Represents a row in the &quot;CDWL_Estrutura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.gov.camara.edemocracia.portlets.wikilegis.model.EstruturaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EstruturaImpl}.
 * </p>
 *
 * @author robson
 * @see EstruturaImpl
 * @see br.gov.camara.edemocracia.portlets.wikilegis.model.Estrutura
 * @see br.gov.camara.edemocracia.portlets.wikilegis.model.EstruturaModel
 * @generated
 */
public class EstruturaModelImpl extends BaseModelImpl<Estrutura>
    implements EstruturaModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a estrutura model instance should use the {@link br.gov.camara.edemocracia.portlets.wikilegis.model.Estrutura} interface instead.
     */
    public static final String TABLE_NAME = "CDWL_Estrutura";
    public static final Object[][] TABLE_COLUMNS = {
            { "estruturaId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "texto", Types.VARCHAR },
            { "ordem", Types.INTEGER },
            { "paiEstruturaId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table CDWL_Estrutura (estruturaId LONG not null primary key,companyId LONG,groupId LONG,texto VARCHAR(300) null,ordem INTEGER,paiEstruturaId LONG)";
    public static final String TABLE_SQL_DROP = "drop table CDWL_Estrutura";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.br.gov.camara.edemocracia.portlets.wikilegis.model.Estrutura"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.br.gov.camara.edemocracia.portlets.wikilegis.model.Estrutura"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.br.gov.camara.edemocracia.portlets.wikilegis.model.Estrutura"),
            true);
    public static long GROUPID_COLUMN_BITMASK = 1L;
    public static long PAIESTRUTURAID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.br.gov.camara.edemocracia.portlets.wikilegis.model.Estrutura"));
    private static ClassLoader _classLoader = Estrutura.class.getClassLoader();
    private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
            Estrutura.class
        };
    private long _estruturaId;
    private long _companyId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private String _texto;
    private int _ordem;
    private long _paiEstruturaId;
    private long _originalPaiEstruturaId;
    private boolean _setOriginalPaiEstruturaId;
    private long _columnBitmask;
    private Estrutura _escapedModelProxy;

    public EstruturaModelImpl() {
    }

    public long getPrimaryKey() {
        return _estruturaId;
    }

    public void setPrimaryKey(long primaryKey) {
        setEstruturaId(primaryKey);
    }

    public Serializable getPrimaryKeyObj() {
        return new Long(_estruturaId);
    }

    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    public Class<?> getModelClass() {
        return Estrutura.class;
    }

    public String getModelClassName() {
        return Estrutura.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("estruturaId", getEstruturaId());
        attributes.put("companyId", getCompanyId());
        attributes.put("groupId", getGroupId());
        attributes.put("texto", getTexto());
        attributes.put("ordem", getOrdem());
        attributes.put("paiEstruturaId", getPaiEstruturaId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long estruturaId = (Long) attributes.get("estruturaId");

        if (estruturaId != null) {
            setEstruturaId(estruturaId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        String texto = (String) attributes.get("texto");

        if (texto != null) {
            setTexto(texto);
        }

        Integer ordem = (Integer) attributes.get("ordem");

        if (ordem != null) {
            setOrdem(ordem);
        }

        Long paiEstruturaId = (Long) attributes.get("paiEstruturaId");

        if (paiEstruturaId != null) {
            setPaiEstruturaId(paiEstruturaId);
        }
    }

    public long getEstruturaId() {
        return _estruturaId;
    }

    public void setEstruturaId(long estruturaId) {
        _estruturaId = estruturaId;
    }

    public long getCompanyId() {
        return _companyId;
    }

    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    public long getGroupId() {
        return _groupId;
    }

    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    public String getTexto() {
        if (_texto == null) {
            return StringPool.BLANK;
        } else {
            return _texto;
        }
    }

    public void setTexto(String texto) {
        _texto = texto;
    }

    public int getOrdem() {
        return _ordem;
    }

    public void setOrdem(int ordem) {
        _ordem = ordem;
    }

    public long getPaiEstruturaId() {
        return _paiEstruturaId;
    }

    public void setPaiEstruturaId(long paiEstruturaId) {
        _columnBitmask |= PAIESTRUTURAID_COLUMN_BITMASK;

        if (!_setOriginalPaiEstruturaId) {
            _setOriginalPaiEstruturaId = true;

            _originalPaiEstruturaId = _paiEstruturaId;
        }

        _paiEstruturaId = paiEstruturaId;
    }

    public long getOriginalPaiEstruturaId() {
        return _originalPaiEstruturaId;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Estrutura.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Estrutura toEscapedModel() {
        if (_escapedModelProxy == null) {
            _escapedModelProxy = (Estrutura) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelProxyInterfaces,
                    new AutoEscapeBeanHandler(this));
        }

        return _escapedModelProxy;
    }

    @Override
    public Object clone() {
        EstruturaImpl estruturaImpl = new EstruturaImpl();

        estruturaImpl.setEstruturaId(getEstruturaId());
        estruturaImpl.setCompanyId(getCompanyId());
        estruturaImpl.setGroupId(getGroupId());
        estruturaImpl.setTexto(getTexto());
        estruturaImpl.setOrdem(getOrdem());
        estruturaImpl.setPaiEstruturaId(getPaiEstruturaId());

        estruturaImpl.resetOriginalValues();

        return estruturaImpl;
    }

    public int compareTo(Estrutura estrutura) {
        long primaryKey = estrutura.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        Estrutura estrutura = null;

        try {
            estrutura = (Estrutura) obj;
        } catch (ClassCastException cce) {
            return false;
        }

        long primaryKey = estrutura.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        EstruturaModelImpl estruturaModelImpl = this;

        estruturaModelImpl._originalGroupId = estruturaModelImpl._groupId;

        estruturaModelImpl._setOriginalGroupId = false;

        estruturaModelImpl._originalPaiEstruturaId = estruturaModelImpl._paiEstruturaId;

        estruturaModelImpl._setOriginalPaiEstruturaId = false;

        estruturaModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Estrutura> toCacheModel() {
        EstruturaCacheModel estruturaCacheModel = new EstruturaCacheModel();

        estruturaCacheModel.estruturaId = getEstruturaId();

        estruturaCacheModel.companyId = getCompanyId();

        estruturaCacheModel.groupId = getGroupId();

        estruturaCacheModel.texto = getTexto();

        String texto = estruturaCacheModel.texto;

        if ((texto != null) && (texto.length() == 0)) {
            estruturaCacheModel.texto = null;
        }

        estruturaCacheModel.ordem = getOrdem();

        estruturaCacheModel.paiEstruturaId = getPaiEstruturaId();

        return estruturaCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(13);

        sb.append("{estruturaId=");
        sb.append(getEstruturaId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", texto=");
        sb.append(getTexto());
        sb.append(", ordem=");
        sb.append(getOrdem());
        sb.append(", paiEstruturaId=");
        sb.append(getPaiEstruturaId());
        sb.append("}");

        return sb.toString();
    }

    public String toXmlString() {
        StringBundler sb = new StringBundler(22);

        sb.append("<model><model-name>");
        sb.append(
            "br.gov.camara.edemocracia.portlets.wikilegis.model.Estrutura");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>estruturaId</column-name><column-value><![CDATA[");
        sb.append(getEstruturaId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>texto</column-name><column-value><![CDATA[");
        sb.append(getTexto());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>ordem</column-name><column-value><![CDATA[");
        sb.append(getOrdem());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>paiEstruturaId</column-name><column-value><![CDATA[");
        sb.append(getPaiEstruturaId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
