package br.gov.camara.edemocracia.portlets.chat.model.impl;

import br.gov.camara.edemocracia.portlets.chat.model.ChatRoom;
import br.gov.camara.edemocracia.portlets.chat.service.ChatRoomLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ChatRoom service. Represents a row in the &quot;CDChat_ChatRoom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChatRoomImpl}.
 * </p>
 *
 * @author Ricardo Lima
 * @see ChatRoomImpl
 * @see br.gov.camara.edemocracia.portlets.chat.model.ChatRoom
 * @generated
 */
public abstract class ChatRoomBaseImpl extends ChatRoomModelImpl
    implements ChatRoom {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a chat room model instance should use the {@link ChatRoom} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ChatRoomLocalServiceUtil.addChatRoom(this);
        } else {
            ChatRoomLocalServiceUtil.updateChatRoom(this);
        }
    }
}
